### ISSUE TITLE
Segfault when removing XEmbed tray

### ISSUE THREAD

**Issue by nick87720z** [rilian-la-te/vala-panel#78]
```
(vala-panel:30697): GLib-GObject-WARNING **: invalid unclassed pointer in cast to 'GtkContainer'

(vala-panel:30697): Gtk-CRITICAL **: gtk_container_remove: assertion 'GTK_IS_CONTAINER (container)' failed

(vala-panel:30697): GLib-GObject-WARNING **: invalid unclassed pointer in cast to 'GtkContainer'

(vala-panel:30697): Gtk-CRITICAL **: gtk_container_remove: assertion 'GTK_IS_CONTAINER (container)' failed

(vala-panel:30697): GLib-GObject-WARNING **: invalid unclassed pointer in cast to 'GtkContainer'

(vala-panel:30697): Gtk-CRITICAL **: gtk_container_remove: assertion 'GTK_IS_CONTAINER (container)' failed

(vala-panel:30697): GLib-GObject-WARNING **: invalid unclassed pointer in cast to 'GtkContainer'

(vala-panel:30697): Gtk-CRITICAL **: gtk_container_remove: assertion 'GTK_IS_CONTAINER (container)' failed

(vala-panel:30697): GLib-GObject-WARNING **: invalid unclassed pointer in cast to 'GtkContainer'

(vala-panel:30697): Gtk-CRITICAL **: gtk_container_remove: assertion 'GTK_IS_CONTAINER (container)' failed

(vala-panel:30697): GLib-GObject-WARNING **: invalid unclassed pointer in cast to 'GtkContainer'

(vala-panel:30697): Gtk-CRITICAL **: gtk_container_remove: assertion 'GTK_IS_CONTAINER (container)' failed

(vala-panel:30697): GLib-GObject-WARNING **: invalid unclassed pointer in cast to 'GtkContainer'

(vala-panel:30697): Gtk-CRITICAL **: gtk_container_remove: assertion 'GTK_IS_CONTAINER (container)' failed

(vala-panel:30697): GLib-GObject-WARNING **: invalid unclassed pointer in cast to 'GtkContainer'

(vala-panel:30697): Gtk-CRITICAL **: gtk_container_add: assertion 'GTK_IS_CONTAINER (container)' failed

(vala-panel:30697): Gdk-CRITICAL **: gdk_window_get_display: assertion 'GDK_IS_WINDOW (window)' failed

(vala-panel:30697): Gdk-CRITICAL **: gdk_x11_display_get_xdisplay: assertion 'GDK_IS_DISPLAY (display)' failed

Thread 1 "vala-panel" received signal SIGSEGV, Segmentation fault.
0x00007ffff6f3c152 in ?? () from /usr/lib64/libgdk-3.so.0
(gdb) backtrace
#0  0x00007ffff6f3c152 in ?? () from /usr/lib64/libgdk-3.so.0
#1  0x00007ffff6f7270e in gdk_x11_window_get_xid () from /usr/lib64/libgdk-3.so.0
#2  0x00007fffd968a7e7 in ?? () from /usr/lib64/vala-panel/applets//libxembed.so
#3  0x00007ffff6f5cff1 in ?? () from /usr/lib64/libgdk-3.so.0
#4  0x00007ffff6f5d2a9 in ?? () from /usr/lib64/libgdk-3.so.0
#5  0x00007ffff6f27739 in gdk_display_get_event () from /usr/lib64/libgdk-3.so.0
#6  0x00007ffff6f5d062 in ?? () from /usr/lib64/libgdk-3.so.0
#7  0x00007ffff7b103e7 in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#8  0x00007ffff7b10650 in ?? () from /usr/lib64/libglib-2.0.so.0
#9  0x00007ffff7b106fc in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#10 0x00007ffff6c084ad in g_application_run () from /usr/lib64/libgio-2.0.so.0
#11 0x00007ffff633d5d1 in __libc_start_main () from /lib64/libc.so.6
#12 0x000000000040385a in ?? ()
#13 0x00007fffffffce08 in ?? ()
#14 0x000000000000001c in ?? ()
#15 0x0000000000000001 in ?? ()
#16 0x00007fffffffd337 in ?? ()
#17 0x0000000000000000 in ?? ()
(gdb) kill
```

**Comment by rilian-la-te** [comment]
More details, please.

**Comment by nick87720z** [comment]
Yeah, no crash anymore)
