### ISSUE TITLE
Crashes under weston

### ISSUE THREAD

**Issue by sunweaver** [rilian-la-te/vala-panel#97]
Filed against Debian BTS, forwarded here: https://bugs.debian.org/894882

Hi,
running vala-panel under weston (e.g. by launching weston from an X11
sesson) makes vala-panel crash:

$ vala-panel

(vala-panel:11471): Gdk-CRITICAL **: 10:29:40.475: gdk_monitor_get_geometry: assertion 'GDK_IS_MONITOR (monitor)' failed

(vala-panel:11471): Gdk-CRITICAL **: 10:29:40.475: gdk_monitor_get_geometry: assertion 'GDK_IS_MONITOR (monitor)' failed

(vala-panel:11471): Gdk-CRITICAL **: 10:29:40.475: gdk_monitor_get_geometry: assertion 'GDK_IS_MONITOR (monitor)' failed

(vala-panel:11471): Gdk-CRITICAL **: 10:29:40.475: gdk_monitor_get_geometry: assertion 'GDK_IS_MONITOR (monitor)' failed

(vala-panel:11471): Gdk-CRITICAL **: 10:29:40.476: gdk_monitor_get_geometry: assertion 'GDK_IS_MONITOR (monitor)' failed
Segmentation fault (core dumped)

(gdb) bt
#0  0x00007f3a065ea77f in XInternAtoms () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#1  0x00007f39efbf7426 in tray_constructor () at /usr/lib/x86_64-linux-gnu/vala-panel/applets//libxembed.so
#2  0x00007f39efbf51b2 in xembed_tray_construct () at /usr/lib/x86_64-linux-gnu/vala-panel/applets//libxembed.so
#3  0x00007f39efbf5359 in  () at /usr/lib/x86_64-linux-gnu/vala-panel/applets//libxembed.so
#4  0x00007f3a07b25373 in vala_panel_layout_place_applet () at /usr/lib/x86_64-linux-gnu/libvalapanel.so.0
#5  0x00007f3a07b25a06 in  () at /usr/lib/x86_64-linux-gnu/libvalapanel.so.0
#6  0x00007f3a08262f6d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007f3a08275d3e in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007f3a0827e3f5 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007f3a0827ee0f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007f3a08262f6d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007f3a08275d3e in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007f3a0827e3f5 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007f3a0827ee0f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007f3a08262f6d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007f3a082758d1 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007f3a0827e3f5 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007f3a0827ee0f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007f3a086e30b5 in peas_engine_load_plugin () at /usr/lib/x86_64-linux-gnu/libpeas-1.0.so.0
#19 0x00007f3a07b24817 in vala_panel_applet_holder_load_applet () at /usr/lib/x86_64-linux-gnu/libvalapanel.so.0
#20 0x00007f3a07b251d2 in vala_panel_layout_init_applets () at /usr/lib/x86_64-linux-gnu/libvalapanel.so.0
#21 0x00007f3a07b2c047 in start_ui () at /usr/lib/x86_64-linux-gnu/libvalapanel.so.0
#22 0x00007f3a07b2c46e in  () at /usr/lib/x86_64-linux-gnu/libvalapanel.so.0
#23 0x00007f3a07b2c5c0 in vala_panel_toplevel_new () at /usr/lib/x86_64-linux-gnu/libvalapanel.so.0
#24 0x000055fe60924d07 in  ()
#25 0x00007f3a07d74050 in g_hash_table_foreach () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x000055fe609251af in  ()
#27 0x000055fe609268e7 in vala_panel_application_activate ()
#28 0x00007f3a08262f6d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#29 0x00007f3a08275ac8 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#30 0x00007f3a0827e3f5 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#31 0x00007f3a0827ee0f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#32 0x000055fe6092566c in  ()
#33 0x00007f3a02b92fce in ffi_call_unix64 () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#34 0x00007f3a02b9293f in ffi_call () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#35 0x00007f3a08263b4d in g_cclosure_marshal_generic_va () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#36 0x00007f3a082631a6 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#37 0x00007f3a0827e0ad in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#38 0x00007f3a0827ee0f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#39 0x00007f3a0a75d923 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#40 0x00007f3a0a75fa68 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#41 0x00007f3a0a75fc26 in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#42 0x00007f3a073e9a87 in __libc_start_main (main=0x55fe609244a0 <main>, argc=1, argv=0x7ffcea82da68, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffcea82da58)
    at ../csu/libc-start.c:310
#43 0x000055fe6092450a in _start ()

It seems to assume there's X11 available. Weston is

$ dpkg -s weston | grep Version
Version: 3.0.0-1

Cheers,

**Comment by rilian-la-te** [comment]
Yes, it will crash if X11 plugins is used under Wayland. Create config without X11 plugins to test.

**Comment by rilian-la-te** [comment]
For now, panel has only partial Wayland support, and cannot determine if plugin is X11 plugin or no.
